# Generated by Django 4.1.3 on 2022-12-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devolu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevolucionCliente',
            new_name='DCliente',
        ),
    ]
